### ISSUE TITLE
Support for inline div w/ SelectionMixin

### ISSUE THREAD

**Issue by leepfrog** [Addepar/ember-table#10]
It would be a great if you could support adding a div underneath the selected row for the SelectionMixin.    I've attached an image to give you an idea of what that might be used for.
![Screen Shot 2012-12-31 at 9 18 55 PM](https://f.cloud.github.com/assets/119997/37133/f8478e54-53d2-11e2-8443-fac6e593b63a.png)

**Comment by Leooo** [comment]
For the ember 1.10, a dirty hack below to be able to expand one line when clicking it (probably better to attach to the mouseover event):

```javascript
Ember.Table.TableRow.reopen({
  forceHeight: null,
  forceTop:null,
  height: Ember.computed(function() {
    return (this.forceHeight==null) ? this.tableComponent.rowHeight : this.forceHeight;
  }).property('forceHeight','tableComponent.rowHeight')
});

Ember.LazyItemView.reopen({
  top: Ember.computed(function() {
    var my_top=this.get('itemIndex') * this.get('rowHeight');
    if (this.forceTop!=null) my_top+=this.forceTop;
    return my_top;
  }).property('forceTop','itemIndex', 'rowHeight')

});

Ember.Table.TableCell.reopen({
  height: Ember.computed.alias('row.height')
});

App.MyTableComponent = Ember.Table.EmberTableComponent.extend({
  getViewForEvent: function(event) {
    var $rowView, view;
    $rowView = $(event.target).parents('.ember-table-table-row');
    view = Ember.View.views[$rowView.attr('id')];
    if (view) {
      return view;
    }
  },
  getNextRowViews: function(itemIndex) {
    var $rowView, view;
    $rowViews = $('.ember-table-table-row');
    var arr=Ember.A();
    $rowViews.each(function(){
      var view = Ember.View.views[$(this).attr('id')];
      if (view.get('itemIndex')>itemIndex) {
        arr.pushObject(view);
      }
    });
    return arr;
  },
  click: function(event) {
    var row_view = this.getViewForEvent(event);
    var $rowView=$(event.target).parents('.ember-table-table-row');
    if (Ember.isEmpty(row_view)) {
      return;
    }
    var itemIndex=row_view.get('itemIndex');
    var nextViews=this.getNextRowViews(itemIndex);
    if (row_view.get('forceHeight')==null) {
      row_view.set('forceHeight','auto');
      var new_height=$rowView.height();
    }
    else {
      row_view.set('forceHeight',null);
      var new_height=null;
    }
    nextViews.forEach(function(view){
      view.set('forceTop',new_height);
    });
    this._super(event);
  }
});
```

Ideally, to be able to display rows with different heights, it would seem more natural to use table, table-row and table-cell displays with position: relative for the rows. But the way it is structured now (re-using html static elements childView in ViewPortDidChange and changing only the content and the top position) forbids to switch to position: relative (top rows couldn't be witched to the bottom).

Is there a fundamental reason why it is structured that way? i.e: would it be too slow to remove first rows html / add new html at the bottom of the table when scrolling down instead of keeping the row and changing it's content? I suspect it is the case, otherwise it would avoid the obligation to calculate each position through ```javascript this.get('itemIndex') * this.get('rowHeight') ```. We could detect when to display a new row when a loader at the bottom gets visible, for example with
```javascript
function isBelowView(elem)
{
    var docViewTop = $(window).scrollTop();
    var docViewBottom = docViewTop + $(window).height();

    var elemTop = $(elem).offset().top;
    var elemBottom = elemTop + $(elem).height();
    return (elemTop > docViewBottom);
}
```
?

**Comment by azirbel** [comment]
That's a good question. Probably you can find more information at https://github.com/emberjs/list-view, which Ember Table is based on.

**Comment by billy-addepar** [comment]
This version of Ember table is no longer supported. If you want to continue discussion, you can open the issue on [Ember Table Legacy](https://github.com/Addepar/ember-table-legacy)
