### ISSUE TITLE
isLastRow property breaks ajax lazy loading tables

### ISSUE THREAD

**Issue by jrhe** [Addepar/ember-table#165]
When doing something along the lines of the Ajax example, because of the isLastRow property, the very last element of content is requested. This subsequently requests the last page of data.

Perhaps a better way to do the isLastRow functionality would be to store an index of the row and compare it to the length? Willing to do a pull request for this if its a good way to go.

**Comment by Leooo** [comment]
Hi, is this issue still current? I'm a third-day user of Ember and want to try ember-table, but the ajax example doesnt render anything (ajax simple was fine), I think this is because of this thread's issue (the index of ObjectAt in the controller starts with the last row, not the first one). Also, the name of this thread maybe should be updated to "ajax cells.." for those who are trying to understand why the examples don't work? Just some suggestions of a newbie, but everyone is a newbie at the beginning..

**Comment by azirbel** [comment]
Hi @Leooo - yep, this is still current. However, the ajax example (http://addepar.github.io/ember-table/#/ember-table/ajax) does work - the issue described here is that ember-table requests the last row of data earlier than necessary. If you're having trouble with the AJAX table, please open a new issue or stack overflow question!

**Comment by Leooo** [comment]
OK thanks for precising this, I forgot to precise I was using the Ember Table ember-1.10 branch with ember 1.10 / htmlbars. If this should work then I must have done something wrong on my side, will work more on this.

**Comment by Leooo** [comment]
Actually now that I'm able to see exceptions in the console I have this one when starting ember-table ajax example:
"TypeError: createChildViews first argument must exist"

I checked that the patch of @gunn referenced in https://github.com/ember-cli/ember-cli/issues/1331 is in my ember-table.js file, so that's not the problem.

Another thing I tried is to rename my app name  from window.App to window.AssessUp, as this seemed to be possibly an issue following the related threads.

Will investigate more, just posting this in case you are familiar with this exception on ember-table. I will be so happy to finally be able to get rid of jquery-datatable which really doesnt marry well with large data sets streamed from the server..

I will create another issue or SO in the next days if I can't solve this.

Using ember-1.10 branch with htmlbars

**Comment by Leooo** [comment]
Got it working by removing the avatar column. Not opening another thread as this is solved on my side. Thanks.

**Comment by Leooo** [comment]
Sidenote for @arzibel: on https://github.com/Addepar/ember-table/commit/c41cfbcc92b220280cf38deb8d8f43b53236ac0c onBodyContentDidChange, onBodyContentDidChange breaks the last content loaded asynchronously (content not loaded into row) if using .on('init').

**Comment by Leooo** [comment]
The commit https://github.com/Addepar/ember-table/commit/c41cfbcc92b220280cf38deb8d8f43b53236ac0c breaks my tables when loading data asynchronously through a model: last row of content is never populated. This is due to the ```onBodyContentDidChange``` observer: if removing ```.on('init')``` seems to solve the issue when loading already existing data, I need to remove the whole observer ```onBodyContentDidChange``` to make it work when filtering data.

**Comment by azirbel** [comment]
Oh, I don't think https://github.com/Addepar/ember-table/commit/c41cfbcc92b220280cf38deb8d8f43b53236ac0c is a very complete/well-formed idea; just a starting point. @Leooo, if you can figure out a more stable solution, I'm happy to look at/merge PRs.

**Comment by Leooo** [comment]
Totally unable to provide a PR or even stable solution at this point as I'm
learning Ember, I'm happy for now when I can find a few fixes. And adding
them here in case others, like me, take the issue list as a starting point
to understand ember(-table).

2015-03-17 18:38 GMT+00:00 Alex Zirbel <notifications@github.com>:

**Comment by cyjia** [comment]
How about create an `lastItem` property on `RowArrayController`?  f77f2e5

**Comment by azirbel** [comment]
Fixed by https://github.com/Addepar/ember-table/pull/320.
