### ISSUE TITLE
How to integrate with Rails Backend?

### ISSUE THREAD

**Issue by kithokit** [Addepar/ember-table#217]
Hi I would like to use ember-table.

I already use ember.js using ember-rails gems.

However, I don't know how to ember-table inside Rails standard application. Even if i include ember-table.js and css into app/assets, it said there is a no. of dependencies need to be included.

is there any tutorial how to install ember-table into rails standard applications? Thanks a lot

**Comment by gnapse** [comment]
Hey @kithokit, did you manage to solve this? I'm having the same issue, and frankly I cannot understand this answer, how would help me.

I too have a rails app using the `ember-rails` gem, and I recently included the `ember-table` addon to the ember app contained within the rails app. The table works, but it shows totally messed up, because the rails app is not loading any css for the `ember-table` component.
