### ISSUE TITLE
Drag/Drop to Reorder Rows

### ISSUE THREAD

**Issue by glennfu** [Addepar/ember-table#241]
I'm trying to rewrite a project in ember and ember-table has been really great so far for it. On my page I have 2 tables, and on the original project, one of the tables used jquery-sortable to let you drag rows of the table around to reorder them. You could also drag rows between the two tables.

I've given a quick shot at implementing jQuery-sortable on an ember-table only to realize it's definitely not the right approach. Since jQuery-sortable's strategy is a view-only approach, which is very non-ember, and all of the rows of ember-table are absolutely positioned, so it really feels like they're completely incompatible. The only way I can imagine such a feature working with ember-table would be if it were written specifically for ember-table.

Has this come up before with the contributors here? I tried doing a search but I haven't been able to find any discussion or attempts at implementing this. Around Google I can find some examples of jquery-sortable + basic Ember code, but nothing that would help get this working. Do you all have any suggestions of what direction to take on this? Thanks!

**Comment by azirbel** [comment]
I agree that a solution would probably have to be written for ember-table. I haven't heard any discussion about reordering rows yet, though it's certainly something that would be great to support!

Unfortunately I don't have much of a suggestion on how to implement it. Probably you'd want something along the lines of an `allowRowReorder` flag added to the API, which when true changes the behavior of clicking on rows. Clicking on rows in this row would "remember" the row; then, drag events would highlight the spaces between rows. Releasing the mouse would tell ember table to change the underlying `content` array to change the order of items.

I realize that suggestion isn't very helpful, since it still involves a lot of custom code that would track mouse dragging and visually indicate the drop location.

We do use jquery-sortable for reordering columns, but as you mentioned rows are much more complex.

**Comment by drglitch** [comment]
@glennfu how about this.... consider your left table being source (dragging FROM) and right table your target (dragging TO).
- you can get the currently selected row from left table via .selected (because to start dragging, you have to click it, so, its selected. Alternatively, implement handler on each row that you hook onto via jquery on didInsertElement
- once drag event started (mouseDown >> mouseMove) clone the ember table row and float that - same as what jqueryDraggable does (https://jqueryui.com/draggable/#snap-to). Be sure to attach the newly cloned row to BODY otherwise all kinds of wierdness will ensue.
- assign RIGHT table as droptarget - you can figure out where it will generally go by taking current first visible row offset * rowHeight, plus offset of your dragged row clone from earlier, and dividing all that by rowHeight - Math.ceil and that should give you the row index you're "floating" over.
... at least in theory. :)

hope this helps

**Comment by DanChadwick** [comment]
I facing this too right now. In light of the intended move from proprietary lazy row rendering to ember-collection, I'm wondering if there are any new ideas. I see a number of drag-and-drop options for ember, but I'm unclear whether they will work with ember-table's rendering.

I am also using financial-table-like indentation, so the drop target isn't just a row, but an indentation level that would be allowed in that row.

**Comment by billy-addepar** [comment]
This version of Ember table is no longer supported. If you want to continue discussion, you can open the issue on [Ember Table Legacy](https://github.com/Addepar/ember-table-legacy)
