### ISSUE TITLE
Thin browser window prevents scrolling all the way to the right

### ISSUE THREAD

**Issue by jiangty-addepar** [Addepar/ember-table#249]
If you open a table with both fixed and scrollable columns that's much wider than the browser width, you lose the ability to scroll all the way to the right.

I couldn't reproduce it exactly on the demo tables, but there's a slightly more convoluted way to repro. I did this on Chrome.
1. Un-maximize a browser, and make it pretty thin (400px or so).
2. Maximize it again and go to http://addepar.github.io/ember-table/#/ember-table/financial.
3. Un-maximize browser again.
Now you can't scroll all the way right.

This is more annoying if you just start out with a very very wide table, in which case you just can't see the rightmost columns.

This is really a bug in antiscroll, which somehow computes the width of the "antiscroll-inner" div incorrectly. Unfortunately it seems like antiscroll hasn't updated in around a year, though...

**Comment by bargar** [comment]
For illustrative purposes, here's the [JS Bin Starter Kit example](http://emberjs.jsbin.com/totomugiqi/1/edit) from README.md as it exhibits the issue:

![reproduce-horizontal-scrolling-problem](https://cloud.githubusercontent.com/assets/1666818/6071613/de07efc2-ad65-11e4-8ae7-99376e6646df.gif)

The resize is triggered by showing/hiding the console pane. Horizontal scrolling works correctly when the table has more space. When the console pane is added in, the scrollbar is rebuilt, but in such a way that it is prevented from moving all the way to the right, and the rightmost table content (the Close column) is unreachable.

**Comment by bargar** [comment]
### Background

For some reason, the antiscroll-inner div corresponding to the horizontal scrollbar (there are two when both scrollbars are present) is not *always* resized properly on a change to the table's dimensions. *Usually*, this div, which for the horizontal scrollbar is invisible, is sized to the same width as the table. In the cases where this fails, and horizontal scrolling is not possible all the way to the right after a resize, this div is *wider* than the ember-table width, which breaks the setting of the calculated value of `innerEl.scrollLeft` below:

```
  /**
   * Called upon drag.
   *
   * @api private
   */

  Scrollbar.Horizontal.prototype.mousemove = function (ev) {
    var trackWidth = this.pane.el.width() - this.pane.padding * 2, 
	    pos = ev.pageX - this.startPageX,
		barWidth = this.el.width(),
		innerEl = this.pane.inner.get(0)

    // minimum top is 0, maximum is the track height
    var y = Math.min(Math.max(pos, 0), trackWidth - barWidth);

    innerEl.scrollLeft = (innerEl.scrollWidth - this.pane.el.width())
      * y / (trackWidth - barWidth);
  };
```

The value calculated is correct, but `scrollLeft` cannot be set to it because ["If set to a value greater than the maximum that the content can be scrolled, scrollLeft is set to the maximum"](https://developer.mozilla.org/en-US/docs/Web/API/Element.scrollLeft#Syntax_and_values). In other words, the value it needs to be is greater than that allowed given the `scrollWidth` and so it is instead set to `scrollWidth`, and some content to the right cannot be reached.

### Solution

Changing this line in the constructor `Antiscroll` in antiscroll.js instead sets the width of this div based on the parent container, which in my tests so far always results in it being the same width as ember-table. 

```
    this.inner.css({
        //'width':  '+=' + (this.y ? scrollbarSize() : 0)
        'width':  this.el.width() + (this.y ? scrollbarSize() : 0)
      , 'height': '+=' + (this.x ? scrollbarSize() : 0)
    });
```

There may well be a more elegant solution (I don't like forcing a width that was badly set in the first place) but I share this in hopes that it helps others finding themselves in this predicament.

**Comment by azirbel** [comment]
@bargar HUGE thank you for all the research you've done here! I'll try to look at this as soon as I can; maybe we can just fork/duplicate antiscroll and include the fix there.

**Comment by billy-addepar** [comment]
This version of Ember table is no longer supported. If you want to continue discussion, you can open the issue on [Ember Table Legacy](https://github.com/Addepar/ember-table-legacy)
