### ISSUE TITLE
Future of Antiscroll as EmberTable dependency

### ISSUE THREAD

**Issue by taras** [Addepar/ember-table#261]
Antiscroll is a pretty significant part of Ember Table's functionality, but the library is not being actively maintained. I asked the author if he'd be interested in having someone else take over the library and he seemed open to it. I want to know if we are planning to continue using this library. If we are, then I'll take on bringing the library up to date and maintaining it. 

What do you think?

**Comment by azirbel** [comment]
This is a great question.

In the short term (next 6 months, probably), there are a number of features, tests, code cleanup, and documentation we'd like to write. We also plan to release a version 1.0.0 of Ember Table. We have no plans to stop using antiscroll during this time.

There are also a few bugs which are a result of antiscroll (e.g. https://github.com/Addepar/ember-table/issues/249), so I'm very excited to hear that you might be able to maintain that library!

In the long term, we haven't decided whether antiscroll is the right solution for ember-table (and we're open to discussion and your opinions). The main considerations are:

* Pro: Antiscroll looks clean, so that even a complex table can scroll both ways and doesn't look cluttered
* Con: Antiscroll looks a bit weird and is unintuitive on e.g. windows machines where scrolling usually doesn't work like that
* Con: Antiscroll is confusing from a UI perspective because it's not clear that scrolling is an option
* Con: Antiscroll can make it difficult to click and drag on the scroll bars

In my mind, these pros and cons come out to pretty even, and I like the feel of the table now. But some people feel differently and would prefer more standard-looking scrollbars.

To get around to answering your question: if you maintain antiscroll, or add bugfixes, your changes will definitely be appreciated by ember-table users for at least 6 months.

If you want to help us find a long-term solution and "figure out" scrolling, you might want to look into alternatives first and see if anything gets your attention. It may be that instead of upgrading antiscroll, you could migrate Ember Table to a different library that better addresses its needs. Or you might find that there isn't really a better option.

**Comment by jiangty-addepar** [comment]
+1 to maintaining antiscroll :)

**Comment by taras** [comment]
@azirbel Thank you for the thoughtful response. I'm leaning towards taking on maintaining the framework at least for 6 months. It will give us an opportunity to learn more about what we need. 

I haven't seen any popular alternatives to it. If they exist, I would love to see what they are. If they do not exist, then our decision is made easier :)

**Comment by azirbel** [comment]
@taras - ok, sounds great!

**Comment by ultimatemonty** [comment]
FWIW I've been using [jquery-slimscroll](https://github.com/rochal/jQuery-slimScroll) in my app and have had very few issues so far. The only real thing that has been a pain is a very slow scroll speed when on mobile browsers (FF, Chrome, Safari all exhibit the issue). Other than that I'm pleased as punch with it.

**Comment by marclundgren** [comment]
@azirbel it seems like [little love](https://github.com/Automattic/antiscroll/graphs/contributors) has gone into the antiscroll project. What are the drawbacks for switching to jquery-slimscroll

**Comment by nylen** [comment]
Please feel free to ping me on PRs that are important to the antiscroll project.

**Comment by billy-addepar** [comment]
This version of Ember table is no longer supported. If you want to continue discussion, you can open the issue on [Ember Table Legacy](https://github.com/Addepar/ember-table-legacy)
