### ISSUE TITLE
Is there anything in the API, now or planned, to move columns from a menu click?

### ISSUE THREAD

**Issue by iwellsltd** [Addepar/ember-table#274]
Hi All, 

I have a requirement to move a column either to the beginning, end, behind previous sibling or after next sibling.

There doesn't seem to be anything like this in the API docs, are there any plans to do this or is there a way I can already do it? I currently have an event plumbed in on a context menu that is within a column header. I was to use events from the user choice on the menu to move a column.

**Comment by azirbel** [comment]
There's nothing in the API, but ideally there doesn't need to be. If I'm not mistaken you just reorder the columns which you've passed into the table, since there's a binding there.

If that doesn't work I'd consider it a minor bug, so we'd be happy to accept a PR to fix it - or you can just call `EmberTableComponent.onColumnSort` and have the table do the reorder for you.
