### ISSUE TITLE
Support for item controllers

### ISSUE THREAD

**Issue by BryanCrotaz** [Addepar/ember-table#297]
I can't find any support for item controllers in the docs. Am I not looking in the right place?

I would have thought there would be an item controller created for each visible row.

**Comment by cwiese** [comment]
Ember.Table.Row is the itemController to Ember.Table.RowArrayController

  bodyContent: Ember.computed(function() {
    return Ember.Table.RowArrayController.create({
      target: this,
      parentController: this,
      container: this.get('container'),
      itemController: Ember.Table.Row,
      content: this.get('content')
    });

**Comment by Twinkletoes** [comment]
How would I override what to provide my own item controller?

**Comment by azirbel** [comment]
We generally don't encourage you to override `Ember.Table.Row` as the item controller, because it's how we handle e.g. selection. Are you sure it's necessary?

If you do need to override it, you'll need to make your own table component and override `bodyContent` (`MyTableComponent = Ember.Table.EmberTableComponent.extend({ bodyContent: ... });`).
