### ISSUE TITLE
Unit Tests?

### ISSUE THREAD

**Issue by jefflage** [Addepar/ember-table#308]
I am looking to potential contribute some enhancements to ember-table.  I have to admit that because of the CS, I never looked in the past but it appears at least now, and maybe because of the migration to ember-cli, that the only until tests in the repo are the 'out of the box' ones that ember / ember-cli auto generate.  Is that true?

If so, and if we were wanting to contribute new functionality, given that ember-cli supports mocha, would you accept mocha-based tests over qunit?

**Comment by azirbel** [comment]
Hi Jeff, great to hear you're thinking of contributing!

You're right, there aren't tests right now. That's coming up in our priority list: (1) merge ember-cli version; (2) release new API; (3) add tests; (4) release version 1.0.0.

We'd like to add qunit-based tests, so that the structure is similar to other Addepar-maintained apps. https://github.com/Addepar/ember-widgets/tree/master/tests is a good example. If you're willing to set up and write some tests in that style, we'd gladly merge them in; I'd recommend writing directly in `ember-table-addon` so you don't have to refactor later.

**Comment by jefflage** [comment]
Cool.  Though we exclusively use mocha internally, I get you're wanting to be consistent in your repo, so we'll go with qunit.  Thanks.

We've forked ember-table-addon and when we have a feature that we think is worth contributing back, we'll submit the PR.
