### ISSUE TITLE
Proper way to deselect a row?

### ISSUE THREAD

**Issue by Yoshi3003** [Addepar/ember-table#328]
Hello,

This may sound trivial but how should I go about deselecting a row? All the demo seems to not have the capability to deselect.

**Comment by HenryVonfire** [comment]
@Yoshi3003 probably is with the function in the component called `setSelected`:

`setSelected: function(row, val) { ... }`

**Comment by Yoshi3003** [comment]
@HenryVonfire Thanks for your answer. I scrolled and saw that function in the ember-table component. However, I do not know the 'ember' way to trigger that function from my controller, without having to modify the code there (or are we users supposed to modify the code anyway?) Forgive me for my noob-ness.

**Comment by HenryVonfire** [comment]
@Yoshi3003 you can extend ember-table to your own component so you can have access to all those functions, override them, etc. without modifying the original addon.

**Comment by Yoshi3003** [comment]
@HenryVonfire Thank you.

**Comment by azirbel** [comment]
A few thoughts:

(1) the way @HenryVonfire suggested sounds good, extending the table component and changing the way `selection` works
(2) often when you use the selection feature, you two-way bind `selection` to your controller. Like `{{ember-table selection=selection}}`. This means that in your controller, you can do `this.set('selection', [])` and ember-table will realize that you have deselected the row.
(3) I think that it should be possible to de-select rows by default in Ember Table, so that when you click on the selected row again it will deselect. I'm happy to accept a PR to fix this.

If you have more questions about this, feel free to reopen this issue.
