### ISSUE TITLE
Presentation error if table consists of 2 cols(1 fixed)

### ISSUE THREAD

**Issue by wuarmin** [Addepar/ember-table#447]
Hello :smile: ,
I encountered following issue:
![grafik](https://user-images.githubusercontent.com/9987680/33014219-e594948a-cde6-11e7-9329-abf7d5fb76bc.png)
You can reproduce it if you set COLUMN_COUNT to 1 at dummy app. 
I think the issue has something to do with vertical scrolling, because if there are just a couple of rows, the issue disappears.
Thank you!

**Comment by billy-addepar** [comment]
@wuarmin: thanks for reporting. I will take a look at this.

**Comment by csukda** [comment]
columns are shown side by side, when width is too big.

look at the screenshot above and to "group 3"
leaf 1 A (this A belongs to leaf 0) A (this A belongs to leaf 1)
leaf 3 A (this A belongs to leaf 2) A (this A belongs to leaf 3)

perhaps this will help you!

**Comment by billy-addepar** [comment]
I am sorry that I have not provided sufficient time to look into this bug yet. This happens when table width is wider than the sum of all columns width. A temporary fix is to define `tableResizeMode` for ember table. Choose `equal_column` if you want the extra space divided equally among all columns.

**Comment by pzuraq** [comment]
This should no longer be an issue on master. @wuarmin let me know if you're still having problems!
