### ISSUE TITLE
Best way to work with multiple versions of ember-table

### ISSUE THREAD

**Issue by RowdyHowell** [Addepar/ember-table#456]
First off, thank you @billy-addepar for picking this project back up!

The project I'm working on uses an older version of ember-table (specifically from #392026052a9b41af49363b2da20c06522ab53e72) in many places in our application.  We want to slowly start converting the tables one-by-one to the new framework.  What is the best way to have both the mentioned and the newest versions of the npm package installed simultaneously?

[NPM suggests](https://github.com/npm/npm/issues/5499) that I should create a new package with a different name that requires the old version (eg. 'ember-table-old' that depends on the 'ember-table' version we currently have).  Is there a better way to do this?

**Comment by billy-addepar** [comment]
@RowdyHowell you can keep both table at the same time. The old table is now referred as ember-table-legacy (link https://github.com/Addepar/ember-table-legacy). You can install that using yarn or npm. 

What we do at our company for the transition is to rename all ember table reference to ember table legacy (e.g. EmberTable -> EmberTableLegacy, ColumnDefinition -> ColumnDefinitionLegacy). After that we can starting using both at the same time and replace tables one by one.

**Comment by billy-addepar** [comment]
Thanks for mentioning this. I will add this migration method to our README

**Comment by RowdyHowell** [comment]
Perfect, thank you!

**Comment by ndantonelli** [comment]
@billy-addepar I am trying to use this migration method to use both versions of ember-table at once.  In my package.json I was using https://github.com/Addepar/ember-table/commit/392026052a9b41af49363b2da20c06522ab53e72 to install the ember-table.  I was using this commit specifically because it has support for ember 1.13.  Now that we are migrating over to ember-table-legacy, I am running into many issues that we did not have before.  I believe it is because ember-table-legacy only supports ember 1.12.  What should we do in this case?

**Comment by billy-addepar** [comment]
@ndantonelli: the commit you pointed to was not `2.0` branch for `ember-table`. It was an attempt to upgrade table to 2.0 but never completed and never tested. I doubt if it works with 1.12. 

Is there any reason you do not want to user master or alpha 1?

**Comment by ndantonelli** [comment]
@billy-addepar: I joined the project using that version of ember-table long after it was added in, so I am not exactly sure what the reasoning was.  I was told that there were some hooks present in that version that we needed to use.  We have never really had any issues with it so we left it alone for a long time, but now we are trying to upgrade to ember 2.0.  I tried adding ember-table-legacy and replacing all of our old references, but I keep getting this error whenever I put cells into the table:
```
Uncaught Error: Property set failed: object in path "tableComponent" could not be found or was destroyed.
```
I looked around and what I found was that this error sometimes occurs because of Ember version issues

**Comment by RowdyHowell** [comment]
We got it going.  Because the code we were working off of was never merged, we forked the repo and renamed the module and references.  Thanks!

**Comment by billy-addepar** [comment]
@ndantonelli do you have still have the issue? If yes, can you post your full stacktrace here? It's hard to know your error root with only one error line.

**Comment by RowdyHowell** [comment]
@billy-addepar @ndantonelli is on my team, we got it. Thanks!
