### ISSUE TITLE
Copy and Paste is not possible with ember table

### ISSUE THREAD

**Issue by tobsch** [Addepar/ember-table#48]
Hi there,

normal HTML-Tables support and paste from browser to excel for example. Ember Table does not.

Is there a way to support it without switching to a real html table?
What was the reason for not taking tables in this project?

Best,

Tobias

**Comment by petrvolny** [comment]
@go1dfish The problem with Handsontable solution is that it uses little Flash snippet on background so implementing it that way would introduce flash dependency in ember table. Not sure if this is what we want. @azirbel any ideas on this one?

**Comment by azirbel** [comment]
I think this needs some API thought. It doesn't even seem very Ember-Table related; Ember Table handles visualizing the table data, but because it's not rendering all the rows, your copy+paste functionality is going to be very limited if you try to copy+paste from rendered DOM elements.

So probably what we want is something that looks like "function for processing `selection` (the Ember Table output) and copying it into the system clipboard". Then you can add a "copy"/"paste" button that uses this function.

As you mentioned, it looks hard to interface with the system clipboard via Javascript (though I haven't looked into it). But I think this is pretty much what we have to do, and it doesn't have to involve Ember Table - we need a way to copy Javascript object data in and out of the system clipboard, and can then interface with Ember Table via `selection`.

**Comment by billy-addepar** [comment]
This version of Ember table is no longer supported. If you want to continue discussion, you can open the issue on [Ember Table Legacy](https://github.com/Addepar/ember-table-legacy)
