### ISSUE TITLE
Key Navigation on Ember Table 2.0

### ISSUE THREAD

**Issue by egabrielsen** [Addepar/ember-table#482]
Currently we are trying to implement an Excel style table with ember-table and were wondering if there was an easy way to do key navigation. currently we are using jquery but would like to steer away from that and do something like: `this.get('cell.targetTable.rows').objectAt(rowIndex).get('cells')` to get nearby cells and focus in on those cells inputs, however the row object does not have access to any of its individual cells.

**Comment by billy-addepar** [comment]
@egabrielsen do you want to access surrounding cells from currently focused cell?

**Comment by egabrielsen** [comment]
Yes

**Comment by billy-addepar** [comment]
Accessing one independent from another is not a good pattern. Can you send action to your controller to set focus input?

**Comment by pzuraq** [comment]
We definitely want to support the ability to do this, but I'm not sure on the API just yet. Part of the issue here is that exposing cells directly could expose a lot of private internal API, and making it queryable like you've proposed could be dangerous. The other side is that because of vertical-collection and occlusion culling, we only have as many cells as are _rendered_, not actually in existence, so it could be confusing when users try to access cells that don't exist.

I think at the moment, you could probably do this using vanilla javascript in a cell component. When detecting the arrow key, use the offset of the cell in its row and the direction to manually focus the corresponding cell in the row above, below, etc. The logic for this will actually probably be very similar to the logic doing it through Ember, but with less overhead.

**Comment by egabrielsen** [comment]
Thanks for the help. The javascript route seems to be working for us as needed and it makes sense that there would be less overhead since we are just selecting/navigating elements of the DOM. We created a mixin for all table cells that handle the keyDown events and then focusIn/select the appropriate cell according to what key they pressed. 

However, another issue arose where tabbing or navigating through the cells horizontally is scrolling the body cells correctly but the header cells do not scroll with the body. It also appears that the horizontal scroll bar is not updating either whenever we bring a cell that is horizontally off screen into focus. Is there any way we can manually update the horizontal scroll for the headers?

**Comment by pzuraq** [comment]
Ah yeah, that would be because Ember Table currently actually has three scroll containers, one for the header/footer/body, and we sync them using the `mousewheel` event rather than the `scroll` event. The reason for this is because doing it on `scroll` will actually cause some visible lag before the containers sync.

I think we could solve this by setting a listener on both `mousewheel` and `scroll`, but it speaks to larger issues here. We're rethinking some of the basic structure we have at the moment, so we'll see if we can come up with a better fix.

**Comment by pzuraq** [comment]
@egabrielsen hey, just wanted to let you know that this shouldn't be an issue with the latest API updates to the table. Tables are now 100% semantically defined, plain old `<table>` tags, and fixed columns/headers/footers are implemented with `position: sticky`. Let us know if you have any more issues!
