### ISSUE TITLE
Is ember-table dependent on ember version

### ISSUE THREAD

**Issue by kalyankiranb** [Addepar/ember-table#495]
Hi,

We are using ember js version 0.1.12.
Can I use ember-table on this version of ember-js?

Thank you

**Comment by pzuraq** [comment]
You may be able to use one of the older versions of Ember Table, but that's a very old version of Ember so we can't be sure. Ember Table 2 supports Ember 1.12.0-3.0.0.

**Comment by kalyankiranb** [comment]
Where can I find the older versions of Ember-Table. Can you please provide me the git link for the same to download? Thank you.

**Comment by pzuraq** [comment]
Older versions are available on NPM on in the history of this repository

**Comment by pzuraq** [comment]
That is a branch that was never merged into master. You should check out git tags

<img width="404" alt="screen shot 2018-02-28 at 1 28 26 pm" src="https://user-images.githubusercontent.com/685518/36814100-6cb7b90e-1c8b-11e8-9109-9c001f4a81bb.png">

**Comment by kalyankiranb** [comment]
Ok. In that case, is this the correct one>
<img width="335" alt="screen shot 2018-02-28 at 1 41 36 pm" src="https://user-images.githubusercontent.com/15140100/36814790-825be2c4-1c8d-11e8-964c-2a4bccdf81b6.png">

**Comment by pzuraq** [comment]
None of those branches is finished, and none of them should be used. If you want to use a previous version of Ember Table, you should use one of the tagged commits on the master branch of this repo. We do not have a formal support matrix for those older versions, so we cannot tell you what versions of Ember they support.

Those branches were also WIP branches to upgrade Ember Table to Ember 1.10.0. You said you are using 0.1.12, are you sure you didn't mean 1.12.0? Because if so, Ember Table 2 _does_ support that version.

**Comment by kalyankiranb** [comment]
The version that I mentioned in my first comment 0.1.12 is of Ember-CLI but not ember-js. The correct ember-js version that we are using is 1.10.1. So, I am trying to find the compatible version of ember-table for my 1.10 ember-js version. Can you please direct me to the correct version of ember-table that is compatible with 1.10 ember-js version?

**Comment by pzuraq** [comment]
Unsure if Ember Table 2 will work with that version of Ember-CLI, but the early alphas should work with 1.10. That will likely change though. You can use [ember-table-legacy](https://www.npmjs.com/package/ember-table-legacy) instead, but it is deprecated and will not be supported in the future.

**Comment by kalyankiranb** [comment]
Ok thank you. I will try that.
