### ISSUE TITLE
make `valuePath` optional

### ISSUE THREAD

**Issue by jamesdixon** [Addepar/ember-table#560]
Hi,

First off, I'm really enjoying this new version of `ember-table`. Well done!

I'm working on converting one of my `ember-light-table` tables to `ember-table` and have a few thoughts, primarily regarding `cellComponent`.

I have many tables that in addition to the data I'm displaying from each row, the row has actions that are tied to icons. For example, I have a table that lists a files that have been uploaded. I have two icons for each row -- one to download the file and another to delete the file. 

The two icons are currently represented by a component and into that component, I pass the actions needing to be triggered by those buttons. 

This lead me to a few thoughts I figured I'd bring up:

1. Is there a possibility of making `valuePath` optional so that you can use a component without it? Using the "download" button as an example, I was forced to pass *something* into `valuePath` even though all I wanted to do was pass the original row back up to my controller when that button was clicked.
2. What are your thoughts on passing both the `row` and `cell` values to the cell component by default? This enables many more possibilities with regards to what a component can do.
3. What do you think of having some sort of `tableActions` hash that can be accessed by default from custom components? Currently, I'm solving this by passing my own `tableActions` hash which is then passed into the custom component. Like the above suggestion, it really opens up a number of possibilities with custom components.

Here's what I'm doing now to solve for the above:

```hbs
{{#ember-table as |t|}}
  {{t.head
    columns=columns
    widthConstraint="eq-container"
    resizeMode="fluid"
    sorts=sorts
    onUpdateSorts=(action (mut sorts))}}

  {{#t.body rows=model as |b|}}
    {{#b.row as |row|}}
      {{#row.cell as |cell column|}}
        {{#if column.cellComponent}}
          {{component column.cellComponent
            tableActions=tableActions
            row=row
            value=cell}}
        {{else}}
          {{cell}}
        {{/if}}
      {{/row.cell}}
    {{/b.row}}
  {{/t.body}}
{{/ember-table}}
```

If there's a better way to do all of this and I'm just missing something, please do let me know 👍 

Thanks for all of your hard work on this!

Cheers.

**Comment by pzuraq** [comment]
Heya, thanks for the feedback!

Definitely agree with regards to `valuePath`, it should be possible to pass a null `valuePath` in or just not define one and have the table default to doing nothing.

> What are your thoughts on passing both the row and cell values to the cell component by default? This enables many more possibilities with regards to what a component can do.

So currently we _do_ yield the row at the cell level:

```hbs
{{#r.cell as |cellValue columnValue rowValue|}}

{{/r.cell}}
```

You can then use the row value however you choose in your own template.

> What do you think of having some sort of tableActions hash that can be accessed by default from custom components? Currently, I'm solving this by passing my own tableActions hash which is then passed into the custom component. Like the above suggestion, it really opens up a number of possibilities with custom components.

So this is actually not really possible for us, because we're actually _not_ in control of the invocation of the `{{component}}` helper. We yield at the cell level, and you call the component helper yourself in your template above, so there's no way for us to add anything to it. This is also why you _do not_ have to call your field on your column definition `cellComponent`. You could name it `foobar` and then use it in your template (not that I'm recommending that):

```hbs
{{#row.cell as |cell column|}}
  {{#if column.foobar}}
    {{component column.foobar
      tableActions=tableActions
      row=row
      value=cell}}
  {{else}}
    {{cell}}
  {{/if}}
{{/row.cell}}
```

This is actually very intentional, because it creates a much more loosely coupled API. Consider the opposite possibility - that we rendered whatever value you passed in `cellComponent` in our own template.

```
<table>
  <tbody>
    {{#each rows as |row|}}
      <tr>
        {{#each columns as |column|}}
          <td>
            {{#if column.cellComponent}}
              {{component column.cellComponent}}
            {{/if}}
          </td>
        {{/each}}
      </tr>
    {{/each}}
  </tbody>
</table>
```

This example is simplified, but at first glance this API seems pretty solid. It allows users to pass in a component to customize the cell by passing in their component. Awesome right?

Except then we realize that users _also_ want to add actions to their cell components (your use case). Now we need to add another field to our column definitions, and we need to pass that into the `component` helper:

```hbs
{{component column.cellComponent tableActions=tableActions}}
```

Then we realize we also need to customize the cell component's class names, and so on. As you can see, our table implementation quickly becomes _very_ tightly bound to the column definition, and we're creating a bunch of cell components based on this API that is communicating through several different layers of abstraction. This is why in general, it's best to avoid rendering user specified components with the `{{component}}` helper (unless they can be closure components, that helps a lot. In our case, they cannot).

Ember Table instead gives complete control to the user, so you can specify whatever API you want and customize these components however you think is best. In some cases, this does mean that you'll have to pass around something like a `tableActions` hash. However, in many cases we can have a cleaner API. 

For instance, in your table, you have two static columns with actions that don't change. I think this would actually be much better off as an `{{if}}` statement than using the component helper:

```hbs
{{#row.cell as |cell column|}}
  {{#if column.isDownload}}
    <button {{action 'download'}}>
	  <i class="download-icon"></i>
    </button>
  {{else if column.isDelete}}
    <button {{action 'delete'}}>
	  <i class="delete-icon"></i>
    </button>
  {{else}}
    {{cell}}
  {{/if}}
{{/row.cell}}
```

Or, we could use a more generalized button specific API on our columns for any button cell:

```hbs
{{#row.cell as |cell column|}}
  {{#if column.isButton}}
    <button {{action column.buttonAction}}>
	  <i class="{{column.button-icon}}"></i>
    </button>
  {{else}}
    {{cell}}
  {{/if}}
{{/row.cell}}
```

As you can see, this is much clearer than passing a `tableActions` hash to the table to deal with. Hope that helps!

**Comment by pzuraq** [comment]
no prob! It definitely is a different way of thinking 😄 

I'm going to keep this issue open for tracking the `valuePath` feature request, will change the title to reflect that

**Comment by jamesdixon** [comment]
@pzuraq sounds great. thanks again!

**Comment by pzuraq** [comment]
Value path should be optional in the latest beta.4!
