### ISSUE TITLE
Use CSSOM for style manipulations

### ISSUE THREAD

**Issue by thegranddesign** [Addepar/ember-table#566]
Inline styling causes CSP violations and I'd much rather just put it in my CSS manually.

Additionally it would be nice to just be able to `@import` the styles in my CSS rather than do inline styles.

**Comment by thegranddesign** [comment]
BTW, no, adding 'unsafe-inline' is not a viable option.

**Comment by pzuraq** [comment]
Unfortunately that’s not an option for us, a large portion of the styles have to be inline. Specifically, fixed columns, fixed headers and footers, and column widths all are accomplished with inline styles.

VerticalCollection also achieves its occlusion through the use of inline styles (manipulating the height of occluded content). I realize the security concerns here, but I don’t think there is a way around this. If you know of a way to dynamically set values like `top`, `left`, `right`, `width`, and `height` without doing it inline please let me know.

**Comment by thegranddesign** [comment]
You should be able to change it via JS yes?

**Comment by pzuraq** [comment]
We actually are changing everything via JS, however we are setting them via `setAttribute` which is not allowed. It appears that using `HTMLElement.style` to set individual properties _is_ allowed, even though the end result is the same. It must do sanitization itself.

I added a note to the MDN on this since it's not documented anywhere, event the CSP spec doesn't explicitly mention it (but it also doesn't explicitly disallow it). Will reopen this and rename, the styles are not optional but we need to use CSSOM to set them.

**Comment by thegranddesign** [comment]
Yes, that’s what I was referring to. Thank you!
