### ISSUE TITLE
Passing boolean attribute to glimmer component doesn't seem to work

### ISSUE THREAD

**Issue by vihai** [Addepar/ember-table#586]
To work around the problem in #584 I wanted to pass @enableTree=false attribute to the body component but I'm getting this error:

```
Uncaught TypeError: EmberTBody#enableTree expected value of type boolean during 'init', but received: 'false'
```

**Comment by pzuraq** [comment]
When using glimmer arguments, anything not wrapped in double curlies is evaluated to a string. In order to pass in a boolean literal, you must wrap the value in curlies:

```
  @enableTable={{false}}
```

This is somewhat counter-intuitive at the moment, I'm not sure if we should allow string values and be somewhat less strict, or if we should enforce boolean values. I'd like to see what the wider ecosystem does before making a call here.

**Comment by vihai** [comment]
Oh, thank you. I didn't try that because I took for granted that {{false}} would refer to an attribute named "false".
