### ISSUE TITLE
Row Selection demo broken

### ISSUE THREAD

**Issue by Techn1x** [Addepar/ember-table#593]
Was just browsing the docs (I'm looking at implementing this table addon) and noticed the checkbox selection is broken in all of the demo's on this page. Even the last demo where you can choose the selection type, "checkboxSelectionMode" doesn't seem to do anything. The checkboxes never get selected on clicking a row or checkbox.

I'm using Chrome 67

http://opensource.addepar.com/ember-table/latest/docs/guides/body/row-selection

**Comment by pzuraq** [comment]
It appears that selection is working, but the check mark is not appearing. It looks like the checkmark svg that we rely on is not loading.

**Comment by kpfefferle** [comment]
I looked into this a bit today, and it seems that this is a bug with how ember-cli-addon-docs and ember-cli-sass are building URLs for the compiled CSS.

Because ember-cli-addon-docs is nesting the built docs for each version under paths such as `/latest/` and `/v2.0.0-beta.1/`, the compiled assets are also nested under these subdirectories in the deployed `gh-pages` branch: https://github.com/Addepar/ember-table/tree/gh-pages

The compiled CSS output, however, is not accounting for the version portion of the nested path. This checkmark SVG is attempting to load from `/ember-table/@addepar/style-toolbox/assets/images/checkmark.svg` when it's actually deployed to `/ember-table/latest/@addepar/style-toolbox/assets/images/checkmark.svg`.
