### ISSUE TITLE
Extending ember-thead: columnTree.rows is undefined

### ISSUE THREAD

**Issue by wynnerd** [Addepar/ember-table#612]
I'm trying to extend ember-thead and ember-table but I'm having some difficulty. When the component tries to calculate `wrappedRows` , `columTree.rows` is returned as undefined.

``` 
@computed('columnTree.rows.[]', 'sorts.[]', 'headerActions.[]', 'fillMode')
  get wrappedRows() {
    let rows = this.get('columnTree.rows');
    let sorts = this.get('sorts');
    let columnMetaCache = this.get('columnMetaCache');

    return emberA(
      rows.map(row => {
//...
```

which is causing this error:
```
component.js:270 Uncaught TypeError: Cannot read property 'map' of undefined
    at Class.get wrappedRows (component.js:270)
    at ComputedPropertyPrototype.get (ember-metal.js:3390)
    at get (ember-metal.js:2761)
    at RootPropertyReference.compute (references.js:176)
    at RootPropertyReference.value (references.js:57)
    at ArrayIterable.iterate (iterable.js:253)
    at IterationArtifacts.isEmpty (reference.js:502)
    at IterablePresenceReference.value (runtime.js:2889)
    at ReferenceCache.initialize (reference.js:395)
    at ReferenceCache.peek (reference.js:369)
```

My template looks like this, and the `my-table` component is drawing `my-thead` component. 
```
{{#my-table as |t|}}
  {{t.head columns=columns}}
{{/my-table}}
```

My thead component.js looks like this
```
import EmberTHead from 'ember-table/components/ember-thead/component';


export default EmberTHead.extend({
});
```

I think the issue is ember-table is exporting everything, and therefore when the columnTree is created my extended component doesn't have access to it. 

When I tried doing the same thing with the normal components I get no errors.
```
{{#ember-table as |t|}}
  {{t.head columns=columns}}
{{/ember-table}}
```

Apologies in advance if this is something really simple, but I just can't understand how I'm supposed to extend this component.

**Comment by drummy2** [comment]
I also have this issue!

**Comment by pzuraq** [comment]
Ember Table components are defined using native classes, so unless you are using the latest versions of Ember you must use native class syntax as well.

Should be noted, it is _not_ recommended that you extend these components to add functionality. As a whole, extending components rather than functionally composing them is an antipattern, and in practical terms your using private APIs to add new functionality, so things could break at any time.

**Comment by wynnerd** [comment]
I'm not exactly sure what you mean by functional composition. Could you elaborate on how I would functionally compose the `ember-thead` component?

**Comment by pzuraq** [comment]
Sure thing! The anti-pattern in question is using inheritance to add functionality. Consider the following class setup:

```js
class SelectComponent extends Component {}

class SelectComponentWithSorting extends SelectComponent {}

class SelectComponentWithDetails extends SelectComponent {}

...
```

In this case, every time we want to add a feature to our Select, we're subclassing the select and adding it to the class. This also likely means we need to duplicate and modify the template. 

As a result of this, the classes are very tightly coupled. Any changes to one class can intimately affect the other classes, and there really isn't a way to distinguish public/private/protected APIs so things will naturally become very intertwined.

By contrast, let's take a look at [ember-power-select's API](https://github.com/cibernox/ember-power-select/blob/master/addon/components/power-select.js#L89-L96). This is not super well documented, but the way that power-select allows you to customize the select component is through a variety of custom component APIs that allow you to pass in a component which, for instance, adds a type of search field, or a different kind of dropdown. Each component is fairly minimal, and fully separated from the other components around it, which makes it much easier to replace.

This is composability at its best. When we reach for a new component C, we find that instead of having to create a new subclass of component A or B, or an entirely new component altogether, we can instead combine A and B with absolutely no changes and have C. When we need to get a variant of C with slight differences, we make a new component D, combine A with D, and we get C'. (Note: I said "functional" composition here because components are in many ways like pure functions, and composability is similar to functional composition in many ways)

That said, not _all_ functionality can be expressed with composable components. Sometimes, functionality is intimately tied to private knowledge only a specific component can have. In Ember Table's case, functionality like sorting columns, reordering and resizing columns, collapsing/uncollapsing tree rows, etc. was all very tied together with the table itself, so it made the most sense to make a monolithic component here. Our goal is to provide the most complete set of these types of features, but allow composition at the _row_ and _cell_ levels, which is where most user's needs diverge. Everyone wants a custom formatted cell type, or row template, or so on.

My recommendation here would be to let us know what you're trying to accomplish by extending the table, so we can see if it is functionality that is fairly common in power tables. If it is, we can add it to the base table component. If it's not, we can try to see if there is a way to implement it without subclassing Ember Table. We likely will not have any semver guarantees for APIs that are only available via subclassing until we can begin using [private fields and methods](https://github.com/tc39/proposal-class-fields#private-fields), which is when we'll be able to actually define what is _public_ and what is _private_.
