### ISSUE TITLE
unhandled exception for computing width in some applications

### ISSUE THREAD

**Issue by efx** [Addepar/ember-table#726]
I've only observed this in our private application that has a number of different components and a complex data flow. I can debug this interactively as I think it would be more efficient than attempting a dummy reproduction. 

https://github.com/Addepar/ember-table/blob/74705ccde9da82fc210dafbcb57cea325eea0d18/addon/-private/column-tree.js#L631 throws an unhandled exception: Assertion Failed: Cannot call get with '_width' on an undefined object. While pausing execution, I also see it throw the same exception when entering this.root.width into the browser console.
The underlying error occurs because of this line https://github.com/Addepar/ember-table/blob/74705ccde9da82fc210dafbcb57cea325eea0d18/addon/-private/column-tree.js#L335 In that case, `meta` is `undefined`.

Both these PRs provide a fix:
#626 
#688 
I verified both versions of the patch in #688 avoid the exception.

**Comment by bantic** [comment]
Thanks for this research. The description here was a helpful catalyst to make a bit of progress on this issue today.
I was able to create a minimal repro:
  * Render a table that has a parent row with many child rows, enough that they will be occluded (i.e., they are past the scroll overflow and do not render)
  * Click the checkbox on the parent row to select it and all its child rows
  * Without scrolling, un-check any child row

After that, this line https://github.com/Addepar/ember-table/blob/0fa3e3f08ce2781bb89bc1d74fdf052bc5bfadd3/addon/-private/collapse-tree.js#L205
will fail an assertion and throw an error with the message:
`Cannot call get with '_parentMeta._rowValue' on an undefined object.`

The error stems from the fact that when the child row's `TableRowMeta#select` method is called, all rows are part of the table's `selection`, but at this line:
https://github.com/Addepar/ember-table/blob/0fa3e3f08ce2781bb89bc1d74fdf052bc5bfadd3/addon/-private/collapse-tree.js#L199
where the code maps every selected row to its `rowMeta`, in order to do some work to determine related selection state (e.g., if any parent row now needs to be un-selected, etc.), not all of the rows in `selection` have materialized `rowMeta` entries yet. A row only has a `rowMeta` created and added to the table's rowMeta cache when the table uses `objectAt` to get the row for rendering (happens [here](https://github.com/Addepar/ember-table/blob/0fa3e3f08ce2781bb89bc1d74fdf052bc5bfadd3/addon/-private/collapse-tree.js#L577) and [here](https://github.com/Addepar/ember-table/blob/0fa3e3f08ce2781bb89bc1d74fdf052bc5bfadd3/addon/-private/collapse-tree.js#L592)).

The fixes in #628 and #688 do avoid the failed assertion, but it appears that they only paper over the problem. If the `undefined` rowMeta's are filtered out then not all the rows in the selection are taken into account when updating the selection groups, and as a result the `selection` property can get out of sync with the selection details stored on the `rowMeta` objects.

I'm going to continue looking into this tomorrow. It looks like we might be able to simply reify all `rowMeta`s when the table `init`s, but if that has too much of a negative performance cost then we will have to do something a little more clever.

**Comment by mixonic** [comment]
I think https://github.com/Addepar/ember-table/pull/727 is a decent start on a real fix.

**Comment by bantic** [comment]
fixed by #727
